### ISSUE TITLE
Runtime.js functions not exposed for precompiled templates

### ISSUE THREAD

**Issue by teddybradford** [monokrome/jaded-brunch#15]
I'm trying to render precompiled Jade templates, but am getting the same error as in #14, `Uncaught ReferenceError: exports is not defined`.

If I'm simply missing something, and precompiled template rendering is indeed working, could someone provide a simple working example for rendering a precompiled template to a DOM element? Perhaps this would be a nice addition to the README as well.

**Comment by monokrome** [comment]
Thanks for the report, @teddybradford. I'm going to mark this as closed as it is a duplicate of #14, but have [posted an issue][jis] on the jade repository because I think that it may be a bug in their runtime file.

Thanks again, and feel free to let me know if you have any ideas in #14.

[jis]: https://github.com/jadejs/jade/issues/1847

**Comment by teddybradford** [comment]
Thank you for looking into this, @monokrome. I appreciate it!

**Comment by monokrome** [comment]
@teddybradford Figured out that we were using the wrong file. Updating today.

**Comment by teddybradford** [comment]
:+1:
